// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Food struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Food) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Players struct {
	Player               []*Player `protobuf:"bytes,1,rep,name=player,proto3" json:"player,omitempty"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (m *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(m, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	UserID               *UserID   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Size                 int32     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Position             *Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction            int32     `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                int32     `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUserID() *UserID {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *Player) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Player) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Player) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Player) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type UserAndSpeed struct {
	UserID               *UserID  `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Speed                int32    `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (m *UserAndSpeed) Reset()         { *m = UserAndSpeed{} }
func (m *UserAndSpeed) String() string { return proto.CompactTextString(m) }
func (*UserAndSpeed) ProtoMessage()    {}
func (*UserAndSpeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *UserAndSpeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndSpeed.Unmarshal(m, b)
}
func (m *UserAndSpeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndSpeed.Marshal(b, m, deterministic)
}
func (m *UserAndSpeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndSpeed.Merge(m, src)
}
func (m *UserAndSpeed) XXX_Size() int {
	return xxx_messageInfo_UserAndSpeed.Size(m)
}
func (m *UserAndSpeed) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndSpeed.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndSpeed proto.InternalMessageInfo

func (m *UserAndSpeed) GetUserID() *UserID {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *UserAndSpeed) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type UserAndDirection struct {
	UserID               *UserID  `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Direction            int32    `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (m *UserAndDirection) Reset()         { *m = UserAndDirection{} }
func (m *UserAndDirection) String() string { return proto.CompactTextString(m) }
func (*UserAndDirection) ProtoMessage()    {}
func (*UserAndDirection) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *UserAndDirection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndDirection.Unmarshal(m, b)
}
func (m *UserAndDirection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndDirection.Marshal(b, m, deterministic)
}
func (m *UserAndDirection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndDirection.Merge(m, src)
}
func (m *UserAndDirection) XXX_Size() int {
	return xxx_messageInfo_UserAndDirection.Size(m)
}
func (m *UserAndDirection) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndDirection.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndDirection proto.InternalMessageInfo

func (m *UserAndDirection) GetUserID() *UserID {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *UserAndDirection) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type UserID struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "game.Position")
	proto.RegisterType((*Food)(nil), "game.Food")
	proto.RegisterType((*Players)(nil), "game.Players")
	proto.RegisterType((*Player)(nil), "game.Player")
	proto.RegisterType((*UserAndSpeed)(nil), "game.UserAndSpeed")
	proto.RegisterType((*UserAndDirection)(nil), "game.UserAndDirection")
	proto.RegisterType((*UserID)(nil), "game.UserID")
	proto.RegisterType((*Error)(nil), "game.Error")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xed, 0x6a, 0xd4, 0x40,
	0x14, 0x4d, 0xd2, 0x24, 0x4d, 0xee, 0xc6, 0x52, 0x2e, 0x52, 0x82, 0x28, 0x2c, 0x83, 0x1f, 0xab,
	0x62, 0x0b, 0x2b, 0x3e, 0x80, 0xd2, 0xba, 0x28, 0xfe, 0x28, 0x09, 0x4a, 0xfb, 0x33, 0x9a, 0x41,
	0x02, 0x6e, 0x26, 0xcc, 0x8c, 0x82, 0x3e, 0x8e, 0x2f, 0xe8, 0x2b, 0xc8, 0xdc, 0x99, 0xcd, 0xee,
	0xe4, 0xc7, 0x76, 0xff, 0xdd, 0x73, 0xef, 0x39, 0xe7, 0x9e, 0x5c, 0x32, 0x00, 0xdf, 0x9b, 0x35,
	0x3f, 0x1f, 0xa4, 0xd0, 0x02, 0x63, 0x53, 0xb3, 0xa7, 0x90, 0x5d, 0x0b, 0xd5, 0xe9, 0x4e, 0xf4,
	0x58, 0x40, 0x78, 0x53, 0x86, 0xf3, 0x70, 0x91, 0x54, 0xe1, 0x8d, 0x41, 0xb7, 0x65, 0x64, 0xd1,
	0x2d, 0x7b, 0x07, 0xf1, 0x7b, 0x21, 0x5a, 0x3c, 0x81, 0xa8, 0x6b, 0x1d, 0x29, 0xea, 0x5a, 0x7c,
	0x01, 0xd9, 0xe0, 0xf4, 0x44, 0x9e, 0x2d, 0x4f, 0xce, 0x69, 0xc9, 0xc6, 0xb5, 0x1a, 0xe7, 0xec,
	0x02, 0x8e, 0xaf, 0x7f, 0x34, 0xbf, 0xb9, 0x54, 0xf8, 0x18, 0xd2, 0x81, 0xca, 0x32, 0x9c, 0x1f,
	0x2d, 0x66, 0xcb, 0xc2, 0x89, 0xa8, 0x57, 0xb9, 0x19, 0xfb, 0x1b, 0x42, 0x6a, 0x5b, 0x46, 0xf0,
	0x53, 0x71, 0xf9, 0xe1, 0x92, 0x76, 0x8f, 0x82, 0xcf, 0xd4, 0xab, 0xdc, 0x0c, 0x11, 0x62, 0xd5,
	0xfd, 0xe1, 0x2e, 0x36, 0xd5, 0x5e, 0xc2, 0xa3, 0xfd, 0x09, 0xf1, 0x21, 0xe4, 0x6d, 0x27, 0xf9,
	0x37, 0x22, 0xc7, 0x64, 0xb2, 0x6d, 0xe0, 0x7d, 0x48, 0xd4, 0xc0, 0x79, 0x5b, 0x26, 0x34, 0xb1,
	0x80, 0x7d, 0x84, 0xc2, 0xa4, 0x78, 0xdb, 0xb7, 0xb5, 0xc1, 0x07, 0x26, 0x1d, 0xbd, 0xa2, 0x5d,
	0xaf, 0x2f, 0x70, 0xea, 0xbc, 0x2e, 0xc7, 0xad, 0x87, 0xf9, 0x79, 0xc9, 0xa3, 0x49, 0x72, 0x36,
	0x87, 0xd4, 0xf2, 0xf1, 0xcc, 0x73, 0x4b, 0x36, 0x7a, 0xf6, 0x08, 0x92, 0x2b, 0x29, 0x85, 0x34,
	0xc1, 0xb8, 0x29, 0x68, 0x9e, 0x57, 0x16, 0x2c, 0xff, 0x45, 0x10, 0xaf, 0x9a, 0x35, 0xc7, 0x05,
	0xe4, 0xb5, 0x6e, 0xa4, 0x26, 0xe0, 0x45, 0x79, 0x30, 0xb3, 0x88, 0x6c, 0x58, 0x80, 0xcf, 0x20,
	0xab, 0xb5, 0x18, 0xee, 0x26, 0xbe, 0x81, 0xa2, 0xe6, 0x7a, 0xfb, 0xc1, 0x67, 0x5b, 0xf2, 0xee,
	0x21, 0xa6, 0xb2, 0x57, 0x90, 0xd5, 0x5c, 0xdb, 0x9b, 0xa3, 0x27, 0xa1, 0xde, 0x94, 0xfe, 0x1c,
	0xf2, 0x15, 0xd7, 0xee, 0x6f, 0xf2, 0xf3, 0x78, 0x3f, 0x1f, 0x0b, 0xf0, 0x25, 0xc0, 0x48, 0x55,
	0x13, 0xee, 0xbd, 0x5d, 0xae, 0x62, 0x01, 0x3e, 0x81, 0xe3, 0x15, 0xd7, 0xf4, 0x36, 0x7c, 0x26,
	0x58, 0x64, 0x26, 0x2c, 0xc0, 0x0b, 0x38, 0x35, 0xd7, 0xf8, 0xd4, 0x29, 0xcd, 0xfb, 0xab, 0x5f,
	0xbc, 0xd7, 0x6a, 0xef, 0x55, 0xbe, 0xa6, 0xf4, 0x4a, 0x5f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x6c, 0xc2, 0xc9, 0xff, 0xb3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	StartGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
	StopGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
	SetDirection(ctx context.Context, in *UserAndDirection, opts ...grpc.CallOption) (*Error, error)
	SetSpeed(ctx context.Context, in *UserAndSpeed, opts ...grpc.CallOption) (*Error, error)
	GetPlayer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Player, error)
	GetPlayers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Players, error)
	GetFood(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Food, error)
	//rpc ListenEvents(UserID) returns (Channel) {}
	StopListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) StartGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) StopGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StopGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) SetDirection(ctx context.Context, in *UserAndDirection, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/SetDirection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) SetSpeed(ctx context.Context, in *UserAndSpeed, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/SetSpeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetPlayer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/game.Game/GetPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetPlayers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/game.Game/GetPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetFood(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Food, error) {
	out := new(Food)
	err := c.cc.Invoke(ctx, "/game.Game/GetFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) StopListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StopListenEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	StartGame(context.Context, *UserID) (*Error, error)
	StopGame(context.Context, *UserID) (*Error, error)
	SetDirection(context.Context, *UserAndDirection) (*Error, error)
	SetSpeed(context.Context, *UserAndSpeed) (*Error, error)
	GetPlayer(context.Context, *UserID) (*Player, error)
	GetPlayers(context.Context, *UserID) (*Players, error)
	GetFood(context.Context, *UserID) (*Food, error)
	//rpc ListenEvents(UserID) returns (Channel) {}
	StopListenEvents(context.Context, *UserID) (*Error, error)
}

// UnimplementedGameServer can be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (*UnimplementedGameServer) StartGame(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedGameServer) StopGame(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopGame not implemented")
}
func (*UnimplementedGameServer) SetDirection(ctx context.Context, req *UserAndDirection) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDirection not implemented")
}
func (*UnimplementedGameServer) SetSpeed(ctx context.Context, req *UserAndSpeed) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpeed not implemented")
}
func (*UnimplementedGameServer) GetPlayer(ctx context.Context, req *UserID) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayer not implemented")
}
func (*UnimplementedGameServer) GetPlayers(ctx context.Context, req *UserID) (*Players, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayers not implemented")
}
func (*UnimplementedGameServer) GetFood(ctx context.Context, req *UserID) (*Food, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFood not implemented")
}
func (*UnimplementedGameServer) StopListenEvents(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopListenEvents not implemented")
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StartGame(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_StopGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StopGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StopGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StopGame(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_SetDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndDirection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SetDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/SetDirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SetDirection(ctx, req.(*UserAndDirection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_SetSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndSpeed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SetSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/SetSpeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SetSpeed(ctx, req.(*UserAndSpeed))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetPlayer(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetPlayers(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetFood(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_StopListenEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StopListenEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StopListenEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StopListenEvents(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _Game_StartGame_Handler,
		},
		{
			MethodName: "StopGame",
			Handler:    _Game_StopGame_Handler,
		},
		{
			MethodName: "SetDirection",
			Handler:    _Game_SetDirection_Handler,
		},
		{
			MethodName: "SetSpeed",
			Handler:    _Game_SetSpeed_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _Game_GetPlayer_Handler,
		},
		{
			MethodName: "GetPlayers",
			Handler:    _Game_GetPlayers_Handler,
		},
		{
			MethodName: "GetFood",
			Handler:    _Game_GetFood_Handler,
		},
		{
			MethodName: "StopListenEvents",
			Handler:    _Game_StopListenEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
