image: "go:1.13"
job:
  script:
    - "go build ."
    - "scp -r . ubuntu@95.163.212.121:/home/l-mozhevikina/back/2019_2_LeMMaS"
before_script:
  - eval "$(ssh-agent -s)"
  - echo "$SSH_KEY" >> ~/.ssh/2019_1_LeMMaS_id_rsa
  - chmod 600 ~/.ssh/2019_1_LeMMaS_id_rsa
  - ssh-add ~/.ssh/2019_1_LeMMaS_id_rsa
  - ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

