language: go
go:
- 1.13.x

notifications:
  email: false

sudo: required

script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 95.163.212.121 >> ~/.ssh/known_hosts
- chmod 600 ./2019_1_LeMMaS_id_rsa
- ssh-add ./2019_1_LeMMaS_id_rsa
- go build .
- scp -r . ubuntu@95.163.212.121:/home/l-mozhevikina/back/2019_2_LeMMaS
before_install:
- pwd
- ls
- ls ~/.ssh
- chmod 600 $HOME/.ssh
- sudo openssl aes-256-cbc -K $encrypted_b973021a3057_key -iv 0
  -in 2019_1_LeMMaS_id_rsa.pem.enc -out ./2019_1_LeMMaS_id_rsa -d
