language: go
go:
- 1.13.x
notifications:
  email: false
sudo: true
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 95.163.212.121 >> $HOME/.ssh/known_hosts
- chmod 600 $HOME/.ssh/2019_1_LeMMaS_id_rsa.pem
- ssh-add $HOME/.ssh/2019_1_LeMMaS_id_rsa.pem
#- ssh -i $HOME/.ssh/2019_1_LeMMaS_id_rsa.pem ubuntu@95.163.212.121 "./backdeploy && exit"
#- scp -r . ubuntu@95.163.212.121:/home/l-mozhevikina/back/2019_2_LeMMaS
before_install:
- openssl aes-256-cbc -K $encrypted_b973021a3057_key -iv $encrypted_b973021a3057_iv
  -in 2019_1_LeMMaS_id_rsa.pem.enc -out $HOME/.ssh/2019_1_LeMMaS_id_rsa.pem -d
branches:
  only: Travis_CD
