// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UserAndError struct {
	User                 *UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserAndError) Reset()         { *m = UserAndError{} }
func (m *UserAndError) String() string { return proto.CompactTextString(m) }
func (*UserAndError) ProtoMessage()    {}
func (*UserAndError) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserAndError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndError.Unmarshal(m, b)
}
func (m *UserAndError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndError.Marshal(b, m, deterministic)
}
func (m *UserAndError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndError.Merge(m, src)
}
func (m *UserAndError) XXX_Size() int {
	return xxx_messageInfo_UserAndError.Size(m)
}
func (m *UserAndError) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndError.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndError proto.InternalMessageInfo

func (m *UserAndError) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserAndError) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SessionID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionID) Reset()         { *m = SessionID{} }
func (m *SessionID) String() string { return proto.CompactTextString(m) }
func (*SessionID) ProtoMessage()    {}
func (*SessionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SessionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionID.Unmarshal(m, b)
}
func (m *SessionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionID.Marshal(b, m, deterministic)
}
func (m *SessionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionID.Merge(m, src)
}
func (m *SessionID) XXX_Size() int {
	return xxx_messageInfo_SessionID.Size(m)
}
func (m *SessionID) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionID.DiscardUnknown(m)
}

var xxx_messageInfo_SessionID proto.InternalMessageInfo

func (m *SessionID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserToUpdate struct {
	User                 *UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserToUpdate) Reset()         { *m = UserToUpdate{} }
func (m *UserToUpdate) String() string { return proto.CompactTextString(m) }
func (*UserToUpdate) ProtoMessage()    {}
func (*UserToUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserToUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToUpdate.Unmarshal(m, b)
}
func (m *UserToUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToUpdate.Marshal(b, m, deterministic)
}
func (m *UserToUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToUpdate.Merge(m, src)
}
func (m *UserToUpdate) XXX_Size() int {
	return xxx_messageInfo_UserToUpdate.Size(m)
}
func (m *UserToUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_UserToUpdate proto.InternalMessageInfo

func (m *UserToUpdate) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type UserToUpdateAvatar struct {
	User                 *UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AvatarFile           []byte    `protobuf:"bytes,2,opt,name=avatarFile,proto3" json:"avatarFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserToUpdateAvatar) Reset()         { *m = UserToUpdateAvatar{} }
func (m *UserToUpdateAvatar) String() string { return proto.CompactTextString(m) }
func (*UserToUpdateAvatar) ProtoMessage()    {}
func (*UserToUpdateAvatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserToUpdateAvatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToUpdateAvatar.Unmarshal(m, b)
}
func (m *UserToUpdateAvatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToUpdateAvatar.Marshal(b, m, deterministic)
}
func (m *UserToUpdateAvatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToUpdateAvatar.Merge(m, src)
}
func (m *UserToUpdateAvatar) XXX_Size() int {
	return xxx_messageInfo_UserToUpdateAvatar.Size(m)
}
func (m *UserToUpdateAvatar) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToUpdateAvatar.DiscardUnknown(m)
}

var xxx_messageInfo_UserToUpdateAvatar proto.InternalMessageInfo

func (m *UserToUpdateAvatar) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserToUpdateAvatar) GetAvatarFile() []byte {
	if m != nil {
		return m.AvatarFile
	}
	return nil
}

type UserName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserName) Reset()         { *m = UserName{} }
func (m *UserName) String() string { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()    {}
func (*UserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserName.Unmarshal(m, b)
}
func (m *UserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserName.Marshal(b, m, deterministic)
}
func (m *UserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserName.Merge(m, src)
}
func (m *UserName) XXX_Size() int {
	return xxx_messageInfo_UserName.Size(m)
}
func (m *UserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserName.DiscardUnknown(m)
}

var xxx_messageInfo_UserName proto.InternalMessageInfo

func (m *UserName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Users struct {
	User                 []*UserData `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUser() []*UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type AvatarUrl struct {
	AvatarUrl            string   `protobuf:"bytes,1,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarUrl) Reset()         { *m = AvatarUrl{} }
func (m *AvatarUrl) String() string { return proto.CompactTextString(m) }
func (*AvatarUrl) ProtoMessage()    {}
func (*AvatarUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *AvatarUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarUrl.Unmarshal(m, b)
}
func (m *AvatarUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarUrl.Marshal(b, m, deterministic)
}
func (m *AvatarUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarUrl.Merge(m, src)
}
func (m *AvatarUrl) XXX_Size() int {
	return xxx_messageInfo_AvatarUrl.Size(m)
}
func (m *AvatarUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarUrl.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarUrl proto.InternalMessageInfo

func (m *AvatarUrl) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type UserAuth struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthData struct {
	SessionID            *SessionID `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthData) Reset()         { *m = AuthData{} }
func (m *AuthData) String() string { return proto.CompactTextString(m) }
func (*AuthData) ProtoMessage()    {}
func (*AuthData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *AuthData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthData.Unmarshal(m, b)
}
func (m *AuthData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthData.Marshal(b, m, deterministic)
}
func (m *AuthData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthData.Merge(m, src)
}
func (m *AuthData) XXX_Size() int {
	return xxx_messageInfo_AuthData.Size(m)
}
func (m *AuthData) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthData.DiscardUnknown(m)
}

var xxx_messageInfo_AuthData proto.InternalMessageInfo

func (m *AuthData) GetSessionID() *SessionID {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *AuthData) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "user.UserData")
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*UserAndError)(nil), "user.UserAndError")
	proto.RegisterType((*SessionID)(nil), "user.SessionID")
	proto.RegisterType((*UserToUpdate)(nil), "user.UserToUpdate")
	proto.RegisterType((*UserToUpdateAvatar)(nil), "user.UserToUpdateAvatar")
	proto.RegisterType((*UserName)(nil), "user.UserName")
	proto.RegisterType((*Users)(nil), "user.Users")
	proto.RegisterType((*AvatarUrl)(nil), "user.AvatarUrl")
	proto.RegisterType((*UserAuth)(nil), "user.UserAuth")
	proto.RegisterType((*AuthData)(nil), "user.AuthData")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0xcd, 0x7c, 0x64, 0x99, 0xd4, 0x0c, 0xab, 0x14, 0x1e, 0x42, 0xd4, 0x45, 0xfb, 0xb4, 0x8b,
	0xee, 0x0a, 0xe3, 0xc1, 0xc3, 0x7a, 0xc9, 0xb2, 0xba, 0x08, 0x8b, 0x48, 0x34, 0xe0, 0xc1, 0x4b,
	0x4b, 0x9a, 0x31, 0x90, 0x49, 0x0f, 0xdd, 0x3d, 0xca, 0xfe, 0x17, 0x7f, 0xac, 0x74, 0x75, 0x3a,
	0x69, 0xb3, 0x08, 0xe3, 0xad, 0x2b, 0xf5, 0xea, 0xd5, 0xe3, 0xbd, 0x22, 0x00, 0x7b, 0x2d, 0xd4,
	0xc5, 0x4e, 0x49, 0x23, 0x71, 0x6e, 0xdf, 0xec, 0x13, 0x2c, 0x4a, 0x2d, 0xd4, 0x35, 0x37, 0x1c,
	0x1f, 0x41, 0x2c, 0xb6, 0xbc, 0x6e, 0xd2, 0xc9, 0xb3, 0xc9, 0x69, 0x52, 0xb8, 0x02, 0x33, 0x58,
	0xec, 0xb8, 0xd6, 0xbf, 0xa4, 0xaa, 0xd2, 0x29, 0x35, 0xfa, 0x1a, 0x11, 0xe6, 0x2d, 0xdf, 0x8a,
	0x74, 0x46, 0xdf, 0xe9, 0xcd, 0x9e, 0x42, 0xfc, 0x4e, 0x29, 0xa9, 0x88, 0xce, 0x3e, 0x7a, 0x3a,
	0x5b, 0xb0, 0x12, 0x56, 0x76, 0x61, 0xde, 0x56, 0x0e, 0xc5, 0x80, 0x84, 0x10, 0x68, 0xb9, 0x3e,
	0xbe, 0x20, 0x85, 0x5e, 0x52, 0x41, 0x3d, 0x7c, 0xee, 0x99, 0xa6, 0x04, 0x5a, 0x3a, 0x10, 0xcd,
	0x7b, 0xda, 0xc7, 0x90, 0x7c, 0x16, 0x5a, 0xd7, 0xb2, 0xfd, 0x70, 0x8d, 0xc7, 0x30, 0xad, 0xab,
	0x6e, 0xed, 0xb4, 0xae, 0xd8, 0xda, 0xed, 0xfc, 0x22, 0xcb, 0x5d, 0xc5, 0x8d, 0x38, 0x64, 0x27,
	0xfb, 0x0a, 0x18, 0xce, 0xe4, 0x3f, 0xb9, 0xe1, 0x87, 0xa9, 0x3d, 0x01, 0xe0, 0x84, 0x7e, 0x5f,
	0x37, 0x82, 0x24, 0xaf, 0x8a, 0xe0, 0x0b, 0x3b, 0x71, 0x96, 0x7f, 0xe4, 0x5b, 0xd1, 0x1b, 0x38,
	0x09, 0x0c, 0x7c, 0x01, 0xb1, 0xed, 0xeb, 0x60, 0xd9, 0xec, 0x9f, 0x32, 0xcf, 0x20, 0x71, 0xd2,
	0x4a, 0xd5, 0xe0, 0x13, 0x48, 0xb8, 0x2f, 0x3a, 0xca, 0xe1, 0x03, 0x7b, 0xeb, 0xf6, 0xe6, 0x7b,
	0xf3, 0xe3, 0xff, 0xa3, 0x66, 0xdf, 0x60, 0x61, 0x27, 0xe9, 0x50, 0xce, 0x21, 0xd1, 0xde, 0xec,
	0xce, 0x8a, 0x07, 0x4e, 0x5d, 0x9f, 0x41, 0x31, 0x20, 0x0e, 0x88, 0x6f, 0xfd, 0x7b, 0x06, 0x73,
	0x2b, 0x0e, 0x2f, 0x01, 0x6f, 0x84, 0xb1, 0xcf, 0xab, 0xbb, 0x21, 0xd0, 0x31, 0x7b, 0x86, 0x83,
	0x19, 0xfe, 0x92, 0x58, 0x84, 0xe7, 0xb0, 0x2a, 0xc4, 0xa6, 0xd6, 0x46, 0x28, 0x22, 0x1b, 0x59,
	0x96, 0x85, 0x9b, 0x59, 0x84, 0xaf, 0x00, 0x5c, 0xb8, 0x04, 0x0e, 0x28, 0x7d, 0xe8, 0xe3, 0x81,
	0x4b, 0x78, 0x38, 0x0c, 0x74, 0x17, 0x91, 0xde, 0x1f, 0x73, 0x9d, 0xf1, 0xf0, 0x4b, 0x58, 0xde,
	0x08, 0x93, 0x37, 0x8d, 0x0b, 0x37, 0xd0, 0x66, 0x2f, 0xc1, 0xa3, 0xa9, 0xc9, 0x22, 0x7c, 0x43,
	0x3e, 0xf4, 0xd1, 0x5e, 0xdd, 0xd1, 0xb9, 0x8c, 0x87, 0x3a, 0x5f, 0x7a, 0x18, 0x8b, 0xf0, 0x0c,
	0xe2, 0x5b, 0xb9, 0xa9, 0xdb, 0x10, 0x6b, 0x83, 0xcb, 0xba, 0xda, 0x87, 0xc8, 0x22, 0x3c, 0x85,
	0xa3, 0x5b, 0xb9, 0x91, 0x7b, 0x73, 0xdf, 0xdf, 0xbf, 0xb5, 0x7f, 0x3f, 0xa2, 0x5f, 0xc6, 0xeb,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0xf3, 0xd9, 0xdc, 0x40, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserBySessionID(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*UserAndError, error)
	RegisterUser(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*Error, error)
	UpdateUser(ctx context.Context, in *UserToUpdate, opts ...grpc.CallOption) (*Error, error)
	UpdateUserAvatar(ctx context.Context, in *UserToUpdateAvatar, opts ...grpc.CallOption) (*Error, error)
	GetAllUsers(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Users, error)
	GetAvatarUrlByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*AvatarUrl, error)
	Login(ctx context.Context, in *UserAuth, opts ...grpc.CallOption) (*AuthData, error)
	Logout(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Error, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserBySessionID(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*UserAndError, error) {
	out := new(UserAndError)
	err := c.cc.Invoke(ctx, "/user.User/GetUserBySessionID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RegisterUser(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UserToUpdate, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserAvatar(ctx context.Context, in *UserToUpdateAvatar, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/UpdateUserAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAllUsers(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/user.User/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAvatarUrlByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*AvatarUrl, error) {
	out := new(AvatarUrl)
	err := c.cc.Invoke(ctx, "/user.User/GetAvatarUrlByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *UserAuth, opts ...grpc.CallOption) (*AuthData, error) {
	out := new(AuthData)
	err := c.cc.Invoke(ctx, "/user.User/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Logout(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUserBySessionID(context.Context, *SessionID) (*UserAndError, error)
	RegisterUser(context.Context, *UserData) (*Error, error)
	UpdateUser(context.Context, *UserToUpdate) (*Error, error)
	UpdateUserAvatar(context.Context, *UserToUpdateAvatar) (*Error, error)
	GetAllUsers(context.Context, *UserName) (*Users, error)
	GetAvatarUrlByName(context.Context, *UserName) (*AvatarUrl, error)
	Login(context.Context, *UserAuth) (*AuthData, error)
	Logout(context.Context, *SessionID) (*Error, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUserBySessionID(ctx context.Context, req *SessionID) (*UserAndError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBySessionID not implemented")
}
func (*UnimplementedUserServer) RegisterUser(ctx context.Context, req *UserData) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserServer) UpdateUser(ctx context.Context, req *UserToUpdate) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServer) UpdateUserAvatar(ctx context.Context, req *UserToUpdateAvatar) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAvatar not implemented")
}
func (*UnimplementedUserServer) GetAllUsers(ctx context.Context, req *UserName) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (*UnimplementedUserServer) GetAvatarUrlByName(ctx context.Context, req *UserName) (*AvatarUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarUrlByName not implemented")
}
func (*UnimplementedUserServer) Login(ctx context.Context, req *UserAuth) (*AuthData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) Logout(ctx context.Context, req *SessionID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserBySessionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserBySessionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUserBySessionID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserBySessionID(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RegisterUser(ctx, req.(*UserData))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UserToUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUpdateAvatar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UpdateUserAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserAvatar(ctx, req.(*UserToUpdateAvatar))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAllUsers(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAvatarUrlByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAvatarUrlByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetAvatarUrlByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAvatarUrlByName(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*UserAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Logout(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBySessionID",
			Handler:    _User_GetUserBySessionID_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _User_RegisterUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateUserAvatar",
			Handler:    _User_UpdateUserAvatar_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _User_GetAllUsers_Handler,
		},
		{
			MethodName: "GetAvatarUrlByName",
			Handler:    _User_GetAvatarUrlByName_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _User_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
