// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	UserId               int32     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Size                 int32     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Direction            int32     `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                int32     `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Position             *Position `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Player) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Player) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Player) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Player) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Food struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Food) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type UserID struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPlayerResult struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerResult) Reset()         { *m = GetPlayerResult{} }
func (m *GetPlayerResult) String() string { return proto.CompactTextString(m) }
func (*GetPlayerResult) ProtoMessage()    {}
func (*GetPlayerResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *GetPlayerResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerResult.Unmarshal(m, b)
}
func (m *GetPlayerResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerResult.Marshal(b, m, deterministic)
}
func (m *GetPlayerResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerResult.Merge(m, src)
}
func (m *GetPlayerResult) XXX_Size() int {
	return xxx_messageInfo_GetPlayerResult.Size(m)
}
func (m *GetPlayerResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerResult proto.InternalMessageInfo

func (m *GetPlayerResult) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type GetPlayersResult struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPlayersResult) Reset()         { *m = GetPlayersResult{} }
func (m *GetPlayersResult) String() string { return proto.CompactTextString(m) }
func (*GetPlayersResult) ProtoMessage()    {}
func (*GetPlayersResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *GetPlayersResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayersResult.Unmarshal(m, b)
}
func (m *GetPlayersResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayersResult.Marshal(b, m, deterministic)
}
func (m *GetPlayersResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayersResult.Merge(m, src)
}
func (m *GetPlayersResult) XXX_Size() int {
	return xxx_messageInfo_GetPlayersResult.Size(m)
}
func (m *GetPlayersResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayersResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayersResult proto.InternalMessageInfo

func (m *GetPlayersResult) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type UserAndSpeed struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Speed                int32    `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAndSpeed) Reset()         { *m = UserAndSpeed{} }
func (m *UserAndSpeed) String() string { return proto.CompactTextString(m) }
func (*UserAndSpeed) ProtoMessage()    {}
func (*UserAndSpeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *UserAndSpeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndSpeed.Unmarshal(m, b)
}
func (m *UserAndSpeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndSpeed.Marshal(b, m, deterministic)
}
func (m *UserAndSpeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndSpeed.Merge(m, src)
}
func (m *UserAndSpeed) XXX_Size() int {
	return xxx_messageInfo_UserAndSpeed.Size(m)
}
func (m *UserAndSpeed) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndSpeed.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndSpeed proto.InternalMessageInfo

func (m *UserAndSpeed) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAndSpeed) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type UserAndDirection struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Direction            int32    `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAndDirection) Reset()         { *m = UserAndDirection{} }
func (m *UserAndDirection) String() string { return proto.CompactTextString(m) }
func (*UserAndDirection) ProtoMessage()    {}
func (*UserAndDirection) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{8}
}

func (m *UserAndDirection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndDirection.Unmarshal(m, b)
}
func (m *UserAndDirection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndDirection.Marshal(b, m, deterministic)
}
func (m *UserAndDirection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndDirection.Merge(m, src)
}
func (m *UserAndDirection) XXX_Size() int {
	return xxx_messageInfo_UserAndDirection.Size(m)
}
func (m *UserAndDirection) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndDirection.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndDirection proto.InternalMessageInfo

func (m *UserAndDirection) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAndDirection) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type GetFoodResult struct {
	Food                 []*Food  `protobuf:"bytes,1,rep,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFoodResult) Reset()         { *m = GetFoodResult{} }
func (m *GetFoodResult) String() string { return proto.CompactTextString(m) }
func (*GetFoodResult) ProtoMessage()    {}
func (*GetFoodResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9}
}

func (m *GetFoodResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFoodResult.Unmarshal(m, b)
}
func (m *GetFoodResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFoodResult.Marshal(b, m, deterministic)
}
func (m *GetFoodResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFoodResult.Merge(m, src)
}
func (m *GetFoodResult) XXX_Size() int {
	return xxx_messageInfo_GetFoodResult.Size(m)
}
func (m *GetFoodResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFoodResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetFoodResult proto.InternalMessageInfo

func (m *GetFoodResult) GetFood() []*Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type Event struct {
	Params               string   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{10}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *Event) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "game.Position")
	proto.RegisterType((*Player)(nil), "game.Player")
	proto.RegisterType((*Food)(nil), "game.Food")
	proto.RegisterType((*UserID)(nil), "game.UserID")
	proto.RegisterType((*Error)(nil), "game.Error")
	proto.RegisterType((*GetPlayerResult)(nil), "game.GetPlayerResult")
	proto.RegisterType((*GetPlayersResult)(nil), "game.GetPlayersResult")
	proto.RegisterType((*UserAndSpeed)(nil), "game.UserAndSpeed")
	proto.RegisterType((*UserAndDirection)(nil), "game.UserAndDirection")
	proto.RegisterType((*GetFoodResult)(nil), "game.GetFoodResult")
	proto.RegisterType((*Event)(nil), "game.Event")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x8b, 0xd3, 0x40,
	0x1c, 0x24, 0x69, 0x92, 0xb6, 0xd3, 0x78, 0x96, 0x55, 0x6b, 0x10, 0x95, 0xba, 0x68, 0x39, 0x3c,
	0x3d, 0x8f, 0x1e, 0x22, 0x08, 0x3e, 0x28, 0x77, 0x96, 0x03, 0x1f, 0x8e, 0x06, 0x9f, 0x25, 0x9a,
	0x55, 0x02, 0xd7, 0x6e, 0xd8, 0xdd, 0x93, 0xab, 0xdf, 0xc3, 0xcf, 0xe0, 0xd7, 0x94, 0xfd, 0xd3,
	0xa4, 0x89, 0x84, 0xfa, 0xb6, 0xb3, 0xf3, 0x9b, 0xcd, 0xec, 0xcc, 0x12, 0xe0, 0x47, 0xb6, 0x62,
	0xc7, 0xa5, 0xe0, 0x8a, 0x93, 0x40, 0xaf, 0xe9, 0x0c, 0x83, 0x4b, 0x2e, 0x0b, 0x55, 0xf0, 0x35,
	0x89, 0xe1, 0xdd, 0x24, 0xde, 0xd4, 0x3b, 0x0c, 0x97, 0xde, 0x8d, 0x46, 0x9b, 0xc4, 0xb7, 0x68,
	0x43, 0x7f, 0x7b, 0x88, 0x2e, 0xaf, 0xb2, 0x0d, 0x13, 0xe4, 0x3e, 0xfa, 0xd7, 0x92, 0x89, 0x2f,
	0x45, 0xee, 0x86, 0x23, 0x0d, 0x2f, 0x72, 0x42, 0x10, 0xc8, 0xe2, 0x17, 0x73, 0x22, 0xb3, 0x26,
	0x0f, 0x31, 0xcc, 0x0b, 0xc1, 0xbe, 0xe9, 0x0f, 0x24, 0x3d, 0x43, 0xd4, 0x1b, 0xe4, 0x2e, 0x42,
	0x59, 0x32, 0x96, 0x27, 0x81, 0x61, 0x2c, 0x20, 0xcf, 0x31, 0x28, 0x9d, 0xa7, 0x24, 0x9c, 0x7a,
	0x87, 0xa3, 0xf9, 0xc1, 0xb1, 0x31, 0xbe, 0x75, 0xba, 0xac, 0x78, 0xfa, 0x01, 0xc1, 0x47, 0xce,
	0x73, 0x72, 0x00, 0xbf, 0xf2, 0xe3, 0x17, 0xcd, 0x33, 0xfc, 0x3d, 0x67, 0x3c, 0x41, 0xf4, 0x59,
	0xdf, 0xe0, 0xac, 0xf3, 0x6a, 0xf4, 0x11, 0xc2, 0x73, 0x21, 0xb8, 0xd0, 0x8e, 0x99, 0x5e, 0x18,
	0x7e, 0xb8, 0xb4, 0x80, 0xbe, 0xc1, 0xed, 0x05, 0x53, 0x36, 0x9f, 0x25, 0x93, 0xd7, 0x57, 0x8a,
	0x3c, 0x45, 0x54, 0x1a, 0x6c, 0x26, 0x47, 0xf3, 0xd8, 0x7d, 0xde, 0xce, 0x38, 0x8e, 0xbe, 0xc5,
	0xb8, 0x12, 0x4a, 0xa7, 0x9c, 0xa1, 0x6f, 0x59, 0x99, 0x78, 0xd3, 0xde, 0x3f, 0xd2, 0x2d, 0x49,
	0xdf, 0x21, 0xd6, 0xb6, 0xdf, 0xaf, 0xf3, 0xd4, 0xc4, 0xd6, 0xd9, 0x4b, 0x95, 0xb2, 0xbf, 0x93,
	0x32, 0xbd, 0xc0, 0xd8, 0xc9, 0xcf, 0xaa, 0x3e, 0x3a, 0x8f, 0x68, 0xd4, 0xe8, 0xb7, 0x6a, 0xa4,
	0xaf, 0x70, 0x6b, 0xc1, 0x94, 0xee, 0xc1, 0x5d, 0xe1, 0x31, 0x82, 0xef, 0x9c, 0xe7, 0xce, 0x3f,
	0xac, 0x7f, 0xc3, 0x9b, 0x7d, 0xfa, 0x1a, 0xe1, 0xf9, 0x4f, 0xb6, 0x56, 0x64, 0x82, 0xa8, 0xcc,
	0x44, 0xb6, 0x92, 0x2e, 0x4f, 0x87, 0xea, 0x98, 0xfd, 0x9d, 0x98, 0xe7, 0x7f, 0x7a, 0x08, 0x16,
	0xd9, 0x8a, 0x91, 0x19, 0x86, 0xa9, 0xca, 0x84, 0x32, 0xc0, 0xc5, 0x63, 0x2b, 0x7c, 0x30, 0xb2,
	0xc8, 0xb6, 0xf5, 0x0c, 0x83, 0x54, 0xf1, 0x72, 0xdf, 0xd8, 0x29, 0xe2, 0x94, 0xa9, 0x3a, 0x86,
	0x49, 0x3d, 0xba, 0x1b, 0x4f, 0x53, 0x74, 0x84, 0x41, 0xca, 0x94, 0x8d, 0x9e, 0x34, 0x04, 0x66,
	0xaf, 0x39, 0x7c, 0x82, 0x61, 0xd5, 0x73, 0xcb, 0xc9, 0x3d, 0x8b, 0xda, 0xef, 0x67, 0x0e, 0xd4,
	0x2f, 0xa3, 0x25, 0x99, 0xb4, 0x24, 0xdb, 0x97, 0xf3, 0x02, 0x7d, 0xd7, 0x43, 0x4b, 0x70, 0xa7,
	0x12, 0xec, 0x94, 0x74, 0x84, 0xf8, 0x53, 0x21, 0x15, 0x5b, 0x9b, 0x2a, 0x64, 0x47, 0x40, 0x9a,
	0x3b, 0xf1, 0xc8, 0x4b, 0x8c, 0x75, 0x92, 0xff, 0x21, 0xd0, 0xf7, 0xfd, 0x1a, 0x99, 0x7f, 0xcc,
	0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x59, 0xae, 0xab, 0x71, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	StartGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
	StopGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
	SetDirection(ctx context.Context, in *UserAndDirection, opts ...grpc.CallOption) (*Error, error)
	SetSpeed(ctx context.Context, in *UserAndSpeed, opts ...grpc.CallOption) (*Error, error)
	GetPlayer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetPlayerResult, error)
	GetPlayers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetPlayersResult, error)
	GetFood(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetFoodResult, error)
	ListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (Game_ListenEventsClient, error)
	StopListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) StartGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) StopGame(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StopGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) SetDirection(ctx context.Context, in *UserAndDirection, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/SetDirection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) SetSpeed(ctx context.Context, in *UserAndSpeed, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/SetSpeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetPlayer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetPlayerResult, error) {
	out := new(GetPlayerResult)
	err := c.cc.Invoke(ctx, "/game.Game/GetPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetPlayers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetPlayersResult, error) {
	out := new(GetPlayersResult)
	err := c.cc.Invoke(ctx, "/game.Game/GetPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetFood(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*GetFoodResult, error) {
	out := new(GetFoodResult)
	err := c.cc.Invoke(ctx, "/game.Game/GetFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) ListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (Game_ListenEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/game.Game/ListenEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameListenEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_ListenEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type gameListenEventsClient struct {
	grpc.ClientStream
}

func (x *gameListenEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) StopListenEvents(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/game.Game/StopListenEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	StartGame(context.Context, *UserID) (*Error, error)
	StopGame(context.Context, *UserID) (*Error, error)
	SetDirection(context.Context, *UserAndDirection) (*Error, error)
	SetSpeed(context.Context, *UserAndSpeed) (*Error, error)
	GetPlayer(context.Context, *UserID) (*GetPlayerResult, error)
	GetPlayers(context.Context, *UserID) (*GetPlayersResult, error)
	GetFood(context.Context, *UserID) (*GetFoodResult, error)
	ListenEvents(*UserID, Game_ListenEventsServer) error
	StopListenEvents(context.Context, *UserID) (*Error, error)
}

// UnimplementedGameServer can be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (*UnimplementedGameServer) StartGame(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedGameServer) StopGame(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopGame not implemented")
}
func (*UnimplementedGameServer) SetDirection(ctx context.Context, req *UserAndDirection) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDirection not implemented")
}
func (*UnimplementedGameServer) SetSpeed(ctx context.Context, req *UserAndSpeed) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpeed not implemented")
}
func (*UnimplementedGameServer) GetPlayer(ctx context.Context, req *UserID) (*GetPlayerResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayer not implemented")
}
func (*UnimplementedGameServer) GetPlayers(ctx context.Context, req *UserID) (*GetPlayersResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayers not implemented")
}
func (*UnimplementedGameServer) GetFood(ctx context.Context, req *UserID) (*GetFoodResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFood not implemented")
}
func (*UnimplementedGameServer) ListenEvents(req *UserID, srv Game_ListenEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListenEvents not implemented")
}
func (*UnimplementedGameServer) StopListenEvents(ctx context.Context, req *UserID) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopListenEvents not implemented")
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StartGame(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_StopGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StopGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StopGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StopGame(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_SetDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndDirection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SetDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/SetDirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SetDirection(ctx, req.(*UserAndDirection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_SetSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndSpeed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SetSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/SetSpeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SetSpeed(ctx, req.(*UserAndSpeed))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetPlayer(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetPlayers(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/GetFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetFood(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_ListenEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).ListenEvents(m, &gameListenEventsServer{stream})
}

type Game_ListenEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type gameListenEventsServer struct {
	grpc.ServerStream
}

func (x *gameListenEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Game_StopListenEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StopListenEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.Game/StopListenEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StopListenEvents(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _Game_StartGame_Handler,
		},
		{
			MethodName: "StopGame",
			Handler:    _Game_StopGame_Handler,
		},
		{
			MethodName: "SetDirection",
			Handler:    _Game_SetDirection_Handler,
		},
		{
			MethodName: "SetSpeed",
			Handler:    _Game_SetSpeed_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _Game_GetPlayer_Handler,
		},
		{
			MethodName: "GetPlayers",
			Handler:    _Game_GetPlayers_Handler,
		},
		{
			MethodName: "GetFood",
			Handler:    _Game_GetFood_Handler,
		},
		{
			MethodName: "StopListenEvents",
			Handler:    _Game_StopListenEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenEvents",
			Handler:       _Game_ListenEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
