version: '2.4'
services:
  web:
    build: images/web
    env_file: ../.env
    working_dir: /home/app/cmd/web
    volumes:
      - ../.:/home/app
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: lemmas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
    ports:
      - 5432:5432

  redis:
    build: images/redis
    expose:
    - 6379