version: '2.4'
services:
  go:
    build: images/go
    working_dir: /home/app
    volumes:
      - ./..:/home/app
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: lemmas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
    ports:
      - 5432:5432
