version: '2.4'
services:
  api:
    build: images/api
    env_file: images/api/.env
    working_dir: /app/cmd/api
    depends_on:
      - auth
    volumes:
      - ../.:/app
    ports:
      - 8080:8080

  auth:
    build: images/auth
    working_dir: /app/cmd/auth
    env_file: images/auth/.env
    volumes:
      - ../.:/app
    expose:
      - 8080

  user:
    build: images/user
    working_dir: /app/cmd/user
    env_file: images/user/.env
    volumes:
      - ../.:/app
    expose:
      - 8080

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: lemmas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
    ports:
      - 5432:5432

  redis:
    build: images/redis
    expose:
      - 6379
