version: '2.4'
services:
  api:
    build: images/api
    working_dir: /app/cmd/api
    volumes:
      - ../.:/app
    env_file: .env
    ports:
      - ${PORT}:${PORT}

  auth:
    build: images/auth
    working_dir: /app/cmd/auth
    volumes:
      - ../.:/app
    env_file: .env
    environment:
      REDIS_DSN: redis://redis:6379
    expose:
      - ${PORT}

  user:
    build: images/user
    working_dir: /app/cmd/user
    volumes:
      - ../.:/app
    env_file: .env
    environment:
      POSTGRES_DSN: host=postgres port=5432 dbname=lemmas user=root password=temppassword
    expose:
      - ${PORT}

  game:
    build: images/game
    working_dir: /app/cmd/game
    volumes:
      - ../.:/app
    env_file: .env
    expose:
      - ${PORT}

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: lemmas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
    ports:
      - 5432:5432

  redis:
    build: images/redis
    expose:
      - 6379
