version: '2.4'
services:
  web:
    build: images/web
    env_file: ../.env
    working_dir: /home/app/cmd/web
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - ../.:/home/app
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: lemmas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
    ports:
      - 5432:5432

  redis:
    build: images/redis
    expose:
    - 6379

  auth_ms:
    build: images/auth_ms
    working_dir: /home/app/microservice/auth/delivery
    volumes:
      - ../.:/home/app
    env_file:
      - ../.env
    restart: on-failure
    depends_on:
      - web
    ports:
      - 8081:8081