// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	Nothing              bool     `protobuf:"varint,1,opt,name=nothing,proto3" json:"nothing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetNothing() bool {
	if m != nil {
		return m.Nothing
	}
	return false
}

type LoginParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginParams) Reset()         { *m = LoginParams{} }
func (m *LoginParams) String() string { return proto.CompactTextString(m) }
func (*LoginParams) ProtoMessage()    {}
func (*LoginParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginParams.Unmarshal(m, b)
}
func (m *LoginParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginParams.Marshal(b, m, deterministic)
}
func (m *LoginParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginParams.Merge(m, src)
}
func (m *LoginParams) XXX_Size() int {
	return xxx_messageInfo_LoginParams.Size(m)
}
func (m *LoginParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginParams.DiscardUnknown(m)
}

var xxx_messageInfo_LoginParams proto.InternalMessageInfo

func (m *LoginParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResult struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type LogoutParams struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutParams) Reset()         { *m = LogoutParams{} }
func (m *LogoutParams) String() string { return proto.CompactTextString(m) }
func (*LogoutParams) ProtoMessage()    {}
func (*LogoutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *LogoutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutParams.Unmarshal(m, b)
}
func (m *LogoutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutParams.Marshal(b, m, deterministic)
}
func (m *LogoutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutParams.Merge(m, src)
}
func (m *LogoutParams) XXX_Size() int {
	return xxx_messageInfo_LogoutParams.Size(m)
}
func (m *LogoutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutParams.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutParams proto.InternalMessageInfo

func (m *LogoutParams) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type RegisterParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterParams) Reset()         { *m = RegisterParams{} }
func (m *RegisterParams) String() string { return proto.CompactTextString(m) }
func (*RegisterParams) ProtoMessage()    {}
func (*RegisterParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *RegisterParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParams.Unmarshal(m, b)
}
func (m *RegisterParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParams.Marshal(b, m, deterministic)
}
func (m *RegisterParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParams.Merge(m, src)
}
func (m *RegisterParams) XXX_Size() int {
	return xxx_messageInfo_RegisterParams.Size(m)
}
func (m *RegisterParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParams proto.InternalMessageInfo

func (m *RegisterParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Nothing)(nil), "auth.Nothing")
	proto.RegisterType((*LoginParams)(nil), "auth.LoginParams")
	proto.RegisterType((*LoginResult)(nil), "auth.LoginResult")
	proto.RegisterType((*LogoutParams)(nil), "auth.LogoutParams")
	proto.RegisterType((*RegisterParams)(nil), "auth.RegisterParams")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0xed, 0xea, 0xf6, 0x6b, 0xac, 0x82, 0x43, 0x0f, 0xcb, 0xe2, 0x41, 0xe2, 0x45, 0x50, 0x2b,
	0x28, 0x9e, 0x45, 0xf0, 0x22, 0x14, 0x91, 0x05, 0xbd, 0x47, 0x0c, 0xd9, 0x40, 0x37, 0x53, 0x32,
	0x09, 0xfe, 0x1a, 0xff, 0xab, 0x98, 0xa4, 0x6b, 0x45, 0xf0, 0xe0, 0x6d, 0xde, 0x9b, 0xb7, 0xb3,
	0xef, 0xbd, 0x00, 0xc8, 0xe0, 0xdb, 0xc5, 0xda, 0x91, 0x27, 0x2c, 0xbf, 0x66, 0x71, 0x02, 0xe3,
	0x47, 0xf2, 0xad, 0xb1, 0x1a, 0x2b, 0x18, 0xdb, 0x34, 0x56, 0xc5, 0x71, 0x71, 0x3a, 0x69, 0x36,
	0x50, 0xdc, 0xc2, 0xde, 0x92, 0xb4, 0xb1, 0x4f, 0xd2, 0xc9, 0x8e, 0x71, 0x0e, 0x43, 0xd5, 0x49,
	0xb3, 0x8a, 0xb2, 0x69, 0x93, 0x00, 0xd6, 0x30, 0x59, 0x4b, 0xe6, 0x77, 0x72, 0x6f, 0xd5, 0x4e,
	0x5c, 0xf4, 0x58, 0x9c, 0xe5, 0x03, 0x8d, 0xe2, 0xb0, 0xf2, 0x78, 0x04, 0x53, 0x56, 0xcc, 0x86,
	0xec, 0xc3, 0x7d, 0x3e, 0xf2, 0x4d, 0x88, 0x73, 0x98, 0x2d, 0x49, 0x53, 0xf0, 0xf9, 0x77, 0x7f,
	0xab, 0x5f, 0xe0, 0xa0, 0x51, 0xda, 0xb0, 0x57, 0xee, 0xbf, 0xf6, 0x10, 0xa1, 0xb4, 0xb2, 0x53,
	0xd5, 0x6e, 0xe4, 0xe3, 0x7c, 0xf5, 0x51, 0x40, 0x79, 0x17, 0x7c, 0x8b, 0x97, 0x30, 0x8c, 0xde,
	0xf1, 0x70, 0x11, 0xdb, 0xdb, 0x6a, 0xa2, 0xde, 0xa6, 0x52, 0x36, 0x31, 0xc0, 0x0b, 0x18, 0x25,
	0xff, 0x88, 0xfd, 0xba, 0x4f, 0x53, 0xef, 0x27, 0x2e, 0x97, 0x2e, 0x06, 0x78, 0x03, 0xb3, 0x4d,
	0x80, 0x67, 0x56, 0x0e, 0xe7, 0x49, 0xf0, 0x33, 0xd4, 0xaf, 0xcf, 0x5e, 0x47, 0xf1, 0x15, 0xaf,
	0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x9c, 0x4b, 0x69, 0xd3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResult, error)
	Logout(ctx context.Context, in *LogoutParams, opts ...grpc.CallOption) (*Nothing, error)
	RegisterUser(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*Nothing, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, "/auth.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutParams, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/auth.Auth/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RegisterUser(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/auth.Auth/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginParams) (*LoginResult, error)
	Logout(context.Context, *LogoutParams) (*Nothing, error)
	RegisterUser(context.Context, *RegisterParams) (*Nothing, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginParams) (*LoginResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Logout(ctx context.Context, req *LogoutParams) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedAuthServer) RegisterUser(ctx context.Context, req *RegisterParams) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RegisterUser(ctx, req.(*RegisterParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Auth_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
