// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginParams) Reset()         { *m = LoginParams{} }
func (m *LoginParams) String() string { return proto.CompactTextString(m) }
func (*LoginParams) ProtoMessage()    {}
func (*LoginParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LoginParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginParams.Unmarshal(m, b)
}
func (m *LoginParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginParams.Marshal(b, m, deterministic)
}
func (m *LoginParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginParams.Merge(m, src)
}
func (m *LoginParams) XXX_Size() int {
	return xxx_messageInfo_LoginParams.Size(m)
}
func (m *LoginParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginParams.DiscardUnknown(m)
}

var xxx_messageInfo_LoginParams proto.InternalMessageInfo

func (m *LoginParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResult struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LogoutParams struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutParams) Reset()         { *m = LogoutParams{} }
func (m *LogoutParams) String() string { return proto.CompactTextString(m) }
func (*LogoutParams) ProtoMessage()    {}
func (*LogoutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *LogoutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutParams.Unmarshal(m, b)
}
func (m *LogoutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutParams.Marshal(b, m, deterministic)
}
func (m *LogoutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutParams.Merge(m, src)
}
func (m *LogoutParams) XXX_Size() int {
	return xxx_messageInfo_LogoutParams.Size(m)
}
func (m *LogoutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutParams.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutParams proto.InternalMessageInfo

func (m *LogoutParams) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResult) Reset()         { *m = LogoutResult{} }
func (m *LogoutResult) String() string { return proto.CompactTextString(m) }
func (*LogoutResult) ProtoMessage()    {}
func (*LogoutResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *LogoutResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResult.Unmarshal(m, b)
}
func (m *LogoutResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResult.Marshal(b, m, deterministic)
}
func (m *LogoutResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResult.Merge(m, src)
}
func (m *LogoutResult) XXX_Size() int {
	return xxx_messageInfo_LogoutResult.Size(m)
}
func (m *LogoutResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResult.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResult proto.InternalMessageInfo

func (m *LogoutResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RegisterParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterParams) Reset()         { *m = RegisterParams{} }
func (m *RegisterParams) String() string { return proto.CompactTextString(m) }
func (*RegisterParams) ProtoMessage()    {}
func (*RegisterParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *RegisterParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParams.Unmarshal(m, b)
}
func (m *RegisterParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParams.Marshal(b, m, deterministic)
}
func (m *RegisterParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParams.Merge(m, src)
}
func (m *RegisterParams) XXX_Size() int {
	return xxx_messageInfo_RegisterParams.Size(m)
}
func (m *RegisterParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParams proto.InternalMessageInfo

func (m *RegisterParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (m *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(m, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

func (m *RegisterResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginParams)(nil), "auth.LoginParams")
	proto.RegisterType((*LoginResult)(nil), "auth.LoginResult")
	proto.RegisterType((*LogoutParams)(nil), "auth.LogoutParams")
	proto.RegisterType((*LogoutResult)(nil), "auth.LogoutResult")
	proto.RegisterType((*RegisterParams)(nil), "auth.RegisterParams")
	proto.RegisterType((*RegisterResult)(nil), "auth.RegisterResult")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0xdd, 0x96, 0x76, 0x14, 0xc1, 0xa1, 0x87, 0x65, 0x41, 0x90, 0x20, 0xe2, 0xc5,
	0x0a, 0xf5, 0xe2, 0x4d, 0xf4, 0x26, 0xf4, 0x20, 0x7b, 0xf0, 0x2a, 0x91, 0x0d, 0xdb, 0x40, 0x77,
	0xa7, 0x64, 0x12, 0x7c, 0x22, 0xdf, 0x53, 0x4c, 0xb2, 0x71, 0xeb, 0x61, 0x0f, 0xbd, 0x65, 0xfe,
	0x99, 0xf9, 0x66, 0xe6, 0x27, 0x00, 0xd2, 0xd9, 0xcd, 0x72, 0x67, 0xc8, 0x12, 0xe6, 0xbf, 0x6f,
	0xf1, 0x04, 0xa7, 0x6b, 0x6a, 0x74, 0xf7, 0x26, 0x8d, 0x6c, 0x19, 0x17, 0x30, 0x51, 0xad, 0xd4,
	0xdb, 0x22, 0xbb, 0xca, 0x6e, 0xe7, 0x55, 0x08, 0xb0, 0x84, 0xd9, 0x4e, 0x32, 0x7f, 0x91, 0xa9,
	0x8b, 0x63, 0x9f, 0x48, 0xb1, 0x78, 0x89, 0x80, 0x4a, 0xb1, 0xdb, 0x5a, 0xbc, 0x04, 0x60, 0xc5,
	0xac, 0xa9, 0xfb, 0xd0, 0x75, 0xa4, 0xcc, 0xa3, 0xf2, 0x5a, 0x7b, 0xbe, 0x31, 0x64, 0x22, 0x26,
	0x04, 0xe2, 0x0e, 0xce, 0xd6, 0xd4, 0x90, 0xb3, 0x71, 0x8b, 0x71, 0x88, 0xb8, 0xee, 0xcb, 0xe3,
	0xcc, 0x04, 0xcd, 0x86, 0xd0, 0x77, 0x38, 0xaf, 0x54, 0xa3, 0xd9, 0x2a, 0x73, 0xe8, 0x71, 0x88,
	0x90, 0x77, 0xb2, 0x55, 0xc5, 0x89, 0xd7, 0xfd, 0x5b, 0xdc, 0xfc, 0x71, 0xc7, 0xe6, 0xaf, 0xbe,
	0x33, 0xc8, 0x9f, 0x9d, 0xdd, 0xe0, 0x3d, 0x4c, 0xbc, 0x43, 0x78, 0xb1, 0xf4, 0xf6, 0x0f, 0xfc,
	0x2e, 0x87, 0x52, 0xa0, 0x89, 0x23, 0x5c, 0xc1, 0x34, 0xdc, 0x87, 0x98, 0xd2, 0xc9, 0x9c, 0x72,
	0x4f, 0x4b, 0x3d, 0x8f, 0x30, 0xeb, 0xb7, 0xc2, 0x45, 0xa8, 0xd8, 0xbf, 0xbe, 0xfc, 0xa7, 0xf6,
	0x9d, 0x9f, 0x53, 0xff, 0x1d, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x95, 0xcc, 0x42, 0x9c,
	0x1c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResult, error)
	Logout(ctx context.Context, in *LogoutParams, opts ...grpc.CallOption) (*LogoutResult, error)
	Register(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*RegisterResult, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, "/auth.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutParams, opts ...grpc.CallOption) (*LogoutResult, error) {
	out := new(LogoutResult)
	err := c.cc.Invoke(ctx, "/auth.Auth/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Register(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, "/auth.Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginParams) (*LoginResult, error)
	Logout(context.Context, *LogoutParams) (*LogoutResult, error)
	Register(context.Context, *RegisterParams) (*RegisterResult, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginParams) (*LoginResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Logout(ctx context.Context, req *LogoutParams) (*LogoutResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedAuthServer) Register(ctx context.Context, req *RegisterParams) (*RegisterResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
