// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserID struct {
	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserData struct {
	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UserAndError struct {
	User  *UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *UserAndError) Reset()         { *m = UserAndError{} }
func (m *UserAndError) String() string { return proto.CompactTextString(m) }
func (*UserAndError) ProtoMessage()    {}
func (*UserAndError) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserAndError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndError.Unmarshal(m, b)
}
func (m *UserAndError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndError.Marshal(b, m, deterministic)
}
func (m *UserAndError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndError.Merge(m, src)
}
func (m *UserAndError) XXX_Size() int {
	return xxx_messageInfo_UserAndError.Size(m)
}
func (m *UserAndError) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndError.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndError proto.InternalMessageInfo

func (m *UserAndError) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserAndError) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SessionID struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *SessionID) Reset()         { *m = SessionID{} }
func (m *SessionID) String() string { return proto.CompactTextString(m) }
func (*SessionID) ProtoMessage()    {}
func (*SessionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SessionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionID.Unmarshal(m, b)
}
func (m *SessionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionID.Marshal(b, m, deterministic)
}
func (m *SessionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionID.Merge(m, src)
}
func (m *SessionID) XXX_Size() int {
	return xxx_messageInfo_SessionID.Size(m)
}
func (m *SessionID) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionID.DiscardUnknown(m)
}

var xxx_messageInfo_SessionID proto.InternalMessageInfo

func (m *SessionID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserToUpdate struct {
	UserID   int32  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *UserToUpdate) Reset()         { *m = UserToUpdate{} }
func (m *UserToUpdate) String() string { return proto.CompactTextString(m) }
func (*UserToUpdate) ProtoMessage()    {}
func (*UserToUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserToUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToUpdate.Unmarshal(m, b)
}
func (m *UserToUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToUpdate.Marshal(b, m, deterministic)
}
func (m *UserToUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToUpdate.Merge(m, src)
}
func (m *UserToUpdate) XXX_Size() int {
	return xxx_messageInfo_UserToUpdate.Size(m)
}
func (m *UserToUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_UserToUpdate proto.InternalMessageInfo

func (m *UserToUpdate) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserToUpdate) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserToUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserToUpdateAvatar struct {
	UserID     int32  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	AvatarFile []byte `protobuf:"bytes,2,opt,name=avatarFile,proto3" json:"avatarFile,omitempty"`
}

func (m *UserToUpdateAvatar) Reset()         { *m = UserToUpdateAvatar{} }
func (m *UserToUpdateAvatar) String() string { return proto.CompactTextString(m) }
func (*UserToUpdateAvatar) ProtoMessage()    {}
func (*UserToUpdateAvatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserToUpdateAvatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToUpdateAvatar.Unmarshal(m, b)
}
func (m *UserToUpdateAvatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToUpdateAvatar.Marshal(b, m, deterministic)
}
func (m *UserToUpdateAvatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToUpdateAvatar.Merge(m, src)
}
func (m *UserToUpdateAvatar) XXX_Size() int {
	return xxx_messageInfo_UserToUpdateAvatar.Size(m)
}
func (m *UserToUpdateAvatar) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToUpdateAvatar.DiscardUnknown(m)
}

var xxx_messageInfo_UserToUpdateAvatar proto.InternalMessageInfo

func (m *UserToUpdateAvatar) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserToUpdateAvatar) GetAvatarFile() []byte {
	if m != nil {
		return m.AvatarFile
	}
	return nil
}

type UserName struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *UserName) Reset()         { *m = UserName{} }
func (m *UserName) String() string { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()    {}
func (*UserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserName.Unmarshal(m, b)
}
func (m *UserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserName.Marshal(b, m, deterministic)
}
func (m *UserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserName.Merge(m, src)
}
func (m *UserName) XXX_Size() int {
	return xxx_messageInfo_UserName.Size(m)
}
func (m *UserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserName.DiscardUnknown(m)
}

var xxx_messageInfo_UserName proto.InternalMessageInfo

func (m *UserName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Users struct {
	User []*UserData `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUser() []*UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type AvatarUrl struct {
	AvatarUrl string `protobuf:"bytes,1,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
}

func (m *AvatarUrl) Reset()         { *m = AvatarUrl{} }
func (m *AvatarUrl) String() string { return proto.CompactTextString(m) }
func (*AvatarUrl) ProtoMessage()    {}
func (*AvatarUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *AvatarUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarUrl.Unmarshal(m, b)
}
func (m *AvatarUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarUrl.Marshal(b, m, deterministic)
}
func (m *AvatarUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarUrl.Merge(m, src)
}
func (m *AvatarUrl) XXX_Size() int {
	return xxx_messageInfo_AvatarUrl.Size(m)
}
func (m *AvatarUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarUrl.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarUrl proto.InternalMessageInfo

func (m *AvatarUrl) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*UserID)(nil), "user.UserID")
	proto.RegisterType((*UserData)(nil), "user.UserData")
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*UserAndError)(nil), "user.UserAndError")
	proto.RegisterType((*SessionID)(nil), "user.SessionID")
	proto.RegisterType((*UserToUpdate)(nil), "user.UserToUpdate")
	proto.RegisterType((*UserToUpdateAvatar)(nil), "user.UserToUpdateAvatar")
	proto.RegisterType((*UserName)(nil), "user.UserName")
	proto.RegisterType((*Users)(nil), "user.Users")
	proto.RegisterType((*AvatarUrl)(nil), "user.AvatarUrl")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0x6e, 0xd3, 0xa6, 0x34, 0x93, 0xd2, 0xf7, 0x18, 0x1e, 0x8f, 0x10, 0xb5, 0xe8, 0x9e, 0x14,
	0xb1, 0x62, 0x3d, 0x78, 0xf0, 0xd4, 0x12, 0x2d, 0x81, 0x22, 0x12, 0x8d, 0xf7, 0x95, 0xec, 0x21,
	0xd0, 0x36, 0x65, 0x37, 0x55, 0xfa, 0x3f, 0xfa, 0x47, 0xc9, 0xce, 0xe6, 0x97, 0x4a, 0x0f, 0xde,
	0xf6, 0x9b, 0xf9, 0xe6, 0x9b, 0x99, 0x6f, 0x58, 0x80, 0xad, 0x12, 0x72, 0xbc, 0x91, 0x59, 0x9e,
	0x61, 0x57, 0xbf, 0x99, 0x07, 0xbd, 0x58, 0x09, 0x19, 0x06, 0x38, 0x04, 0x2b, 0x0c, 0xbc, 0xf6,
	0x71, 0xfb, 0xd4, 0x8e, 0xac, 0x30, 0x60, 0x8f, 0xd0, 0xd7, 0x99, 0x80, 0xe7, 0x1c, 0xff, 0x81,
	0x2d, 0x56, 0x3c, 0x5d, 0x52, 0xda, 0x89, 0x0c, 0x40, 0x1f, 0xfa, 0x1b, 0xae, 0xd4, 0x7b, 0x26,
	0x13, 0xcf, 0xa2, 0x44, 0x85, 0x11, 0xa1, 0xbb, 0xe6, 0x2b, 0xe1, 0x75, 0x28, 0x4e, 0x6f, 0x76,
	0x04, 0xf6, 0x9d, 0x94, 0x99, 0x24, 0x39, 0xfd, 0xa8, 0xe4, 0x34, 0x60, 0x31, 0x0c, 0x74, 0xc3,
	0xe9, 0x3a, 0x31, 0x2c, 0x06, 0x34, 0x22, 0x91, 0xdc, 0xc9, 0x70, 0x4c, 0xb3, 0x97, 0x23, 0x45,
	0x94, 0xc3, 0x93, 0x52, 0xc9, 0x22, 0x92, 0x6b, 0x48, 0x54, 0x5f, 0xca, 0x1e, 0x80, 0xf3, 0x24,
	0x94, 0x4a, 0xb3, 0xb5, 0x59, 0x32, 0x4d, 0x8a, 0xb6, 0x56, 0x9a, 0xb0, 0x17, 0xd3, 0xf3, 0x39,
	0x8b, 0x37, 0x09, 0xcf, 0x05, 0xfe, 0x87, 0xde, 0x96, 0xec, 0x28, 0x8c, 0x28, 0xd0, 0xaf, 0x57,
	0x5d, 0x00, 0x36, 0x75, 0xa7, 0x6f, 0x3c, 0xe7, 0x72, 0xaf, 0xfa, 0x08, 0x80, 0x13, 0xe3, 0x3e,
	0x5d, 0x0a, 0xd2, 0x1f, 0x44, 0x8d, 0x08, 0x1b, 0x99, 0x53, 0x3c, 0xf0, 0x95, 0xa8, 0xba, 0xb5,
	0x1b, 0xdd, 0xce, 0xc1, 0xd6, 0x79, 0xd5, 0xb0, 0xac, 0xb3, 0xcf, 0x32, 0x76, 0x06, 0x8e, 0x19,
	0x27, 0x96, 0x4b, 0x3c, 0x04, 0x87, 0x97, 0xa0, 0x90, 0xac, 0x03, 0x93, 0x0f, 0x0b, 0xba, 0xba,
	0x1a, 0xaf, 0xc0, 0x9d, 0x8b, 0x5c, 0x3f, 0x67, 0xbb, 0x30, 0xc0, 0x41, 0x2d, 0x1c, 0x06, 0x3e,
	0xd6, 0xa8, 0xbc, 0x1d, 0x6b, 0xe1, 0x2d, 0x60, 0x55, 0x52, 0xfb, 0xff, 0xc7, 0x70, 0xab, 0xc0,
	0x9e, 0xe2, 0x4b, 0x00, 0x63, 0x1c, 0x75, 0x6f, 0x70, 0x4a, 0x43, 0xfd, 0xe6, 0xa5, 0xa9, 0xdb,
	0xdf, 0xba, 0xa0, 0x70, 0xdb, 0xfb, 0x59, 0x66, 0x32, 0xdf, 0x8b, 0x2f, 0x60, 0x38, 0x17, 0xf9,
	0x42, 0xf0, 0x44, 0x48, 0xe3, 0xe3, 0xd7, 0x05, 0xdd, 0x1a, 0x29, 0xd6, 0xc2, 0x1b, 0xda, 0xac,
	0xf2, 0x70, 0xb6, 0xa3, 0xbb, 0x34, 0xcc, 0xd6, 0xd8, 0x2f, 0x36, 0xad, 0x68, 0xac, 0xf5, 0xda,
	0xa3, 0x8f, 0x77, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x99, 0xaa, 0x1b, 0x52, 0x86, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserAndError, error)
	GetUserBySessionID(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*UserAndError, error)
	UpdateUser(ctx context.Context, in *UserToUpdate, opts ...grpc.CallOption) (*Error, error)
	UpdateUserAvatar(ctx context.Context, in *UserToUpdateAvatar, opts ...grpc.CallOption) (*Error, error)
	GetLeaderUsers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Users, error)
	GetAvatarUrlByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*AvatarUrl, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserAndError, error) {
	out := new(UserAndError)
	err := c.cc.Invoke(ctx, "/user.User/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserBySessionID(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*UserAndError, error) {
	out := new(UserAndError)
	err := c.cc.Invoke(ctx, "/user.User/GetUserBySessionID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UserToUpdate, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserAvatar(ctx context.Context, in *UserToUpdateAvatar, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/user.User/UpdateUserAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetLeaderUsers(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/user.User/GetLeaderUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAvatarUrlByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*AvatarUrl, error) {
	out := new(AvatarUrl)
	err := c.cc.Invoke(ctx, "/user.User/GetAvatarUrlByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the delivery API for User service.
type UserServer interface {
	GetUserByID(context.Context, *UserID) (*UserAndError, error)
	GetUserBySessionID(context.Context, *SessionID) (*UserAndError, error)
	UpdateUser(context.Context, *UserToUpdate) (*Error, error)
	UpdateUserAvatar(context.Context, *UserToUpdateAvatar) (*Error, error)
	GetLeaderUsers(context.Context, *UserID) (*Users, error)
	GetAvatarUrlByName(context.Context, *UserName) (*AvatarUrl, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUserByID(ctx context.Context, req *UserID) (*UserAndError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (*UnimplementedUserServer) GetUserBySessionID(ctx context.Context, req *SessionID) (*UserAndError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBySessionID not implemented")
}
func (*UnimplementedUserServer) UpdateUser(ctx context.Context, req *UserToUpdate) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServer) UpdateUserAvatar(ctx context.Context, req *UserToUpdateAvatar) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAvatar not implemented")
}
func (*UnimplementedUserServer) GetLeaderUsers(ctx context.Context, req *UserID) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderUsers not implemented")
}
func (*UnimplementedUserServer) GetAvatarUrlByName(ctx context.Context, req *UserName) (*AvatarUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarUrlByName not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserBySessionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserBySessionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUserBySessionID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserBySessionID(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UserToUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUpdateAvatar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UpdateUserAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserAvatar(ctx, req.(*UserToUpdateAvatar))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetLeaderUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetLeaderUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetLeaderUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetLeaderUsers(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAvatarUrlByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAvatarUrlByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetAvatarUrlByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAvatarUrlByName(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByID",
			Handler:    _User_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserBySessionID",
			Handler:    _User_GetUserBySessionID_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateUserAvatar",
			Handler:    _User_UpdateUserAvatar_Handler,
		},
		{
			MethodName: "GetLeaderUsers",
			Handler:    _User_GetLeaderUsers_Handler,
		},
		{
			MethodName: "GetAvatarUrlByName",
			Handler:    _User_GetAvatarUrlByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
